@base=http://localhost:3002
 
### Create a new item
 
POST {{base}}/users
Content-Type: application/json
 
{
  "name":"Joe"
}
 
### Get All items
 
GET {{base}}/users
 
### Get Specific item
 
GET {{base}}/users/2
Content-Type: application/json
 
### Delete item
 
DELETE {{base}}/users/4